### ISSUE TITLE
xgboost/adaboost nrounds parameter

### ISSUE THREAD

**Issue by pfistfl** [PGijsbers/symbolicdefaults#3]
In order to avoid the problem where larger is usually always better, we could set 
the following parameters to a constant.

`xgboost: nrounds`: 500? 1000? 
`adaboost: n_estimators `: 500?

This has some advantages:
- Results are comparable more easily wrt. runtime, as they generally have more or less equivalent runtimes (save for depth of boosted trees)
- We alleviate the outside of existing metadata problem

If we want fully symbolic defaults in the end, we could alleviate the restriction towards the end.

**Comment by PGijsbers** [comment]
That might be a good idea. Note though that for xgboost (with linear models), I found a symbolic expression of `n` the number of rounds. This had a min/median/max of respectively 552/2109/45312 (if I can read my squiggly notes) - in many cases not outside of the max of 5000 in the metadataset!
That said, the defaults altogether were terrible, so maybe we should start with a simplified problem and setting a constant value for this problem is a good start too.

**Comment by pfistfl** [comment]
Solved via #10
